// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VetClinicAPI.Models;

#nullable disable

namespace VetClinicAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251204195051_InitialSeed")]
    partial class InitialSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("VetClinicAPI.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MicrochipId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VetDoctorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VetDoctorId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MicrochipId = "MC1001",
                            Name = "Buddy",
                            Species = "Dog",
                            VetDoctorId = 1
                        },
                        new
                        {
                            Id = 2,
                            MicrochipId = "MC1002",
                            Name = "Whiskers",
                            Species = "Cat",
                            VetDoctorId = 2
                        },
                        new
                        {
                            Id = 3,
                            MicrochipId = "MC1003",
                            Name = "Chirpy",
                            Species = "Bird",
                            VetDoctorId = 3
                        },
                        new
                        {
                            Id = 4,
                            MicrochipId = "MC1004",
                            Name = "Nibbles",
                            Species = "Rabbit",
                            VetDoctorId = 1
                        });
                });

            modelBuilder.Entity("VetClinicAPI.Models.PetProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VetNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PetId")
                        .IsUnique();

                    b.ToTable("PetProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PetId = 1,
                            VetNotes = "Healthy, needs annual vaccination."
                        },
                        new
                        {
                            Id = 2,
                            PetId = 2,
                            VetNotes = "Dental cleaning scheduled next month."
                        },
                        new
                        {
                            Id = 3,
                            PetId = 3,
                            VetNotes = "Feather condition normal, check diet."
                        },
                        new
                        {
                            Id = 4,
                            PetId = 4,
                            VetNotes = "Monitor weight, eating well."
                        });
                });

            modelBuilder.Entity("VetClinicAPI.Models.VetDoctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VetDoctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dr. Alice Smith",
                            Specialty = "Surgery"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dr. Bob Johnson",
                            Specialty = "Dentistry"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dr. Carol Lee",
                            Specialty = "Dermatology"
                        });
                });

            modelBuilder.Entity("VetClinicAPI.Models.Pet", b =>
                {
                    b.HasOne("VetClinicAPI.Models.VetDoctor", "VetDoctor")
                        .WithMany("Pets")
                        .HasForeignKey("VetDoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VetDoctor");
                });

            modelBuilder.Entity("VetClinicAPI.Models.PetProfile", b =>
                {
                    b.HasOne("VetClinicAPI.Models.Pet", "Pet")
                        .WithOne("PetProfile")
                        .HasForeignKey("VetClinicAPI.Models.PetProfile", "PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("VetClinicAPI.Models.Pet", b =>
                {
                    b.Navigation("PetProfile");
                });

            modelBuilder.Entity("VetClinicAPI.Models.VetDoctor", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
